services:
  compute:
    image: data-science-python
    build:
      context: .
      args:
        DEV: true
        BUILDKIT_PROGRESS: plain
    volumes:
      - ./app:/app
    ports:
      - "8888:8888"
    command: jupyter lab --ip=0.0.0.0 --port=8888